title: Assistive Tech Workshop
description: Explore the assistive technology built into your computer

theme: just-the-docs
url: https://elichad.github.io/assistive-tech-workshop
aux_links:
  GitHub: https://elichad.github.io/assistive-tech-workshop/
