title: Explore the assistive technology built into your computer
description: Assistive technology learning resources which can be used for workshops or self-study

theme: just-the-docs
url: https://elichad.github.io/assistive-tech-workshop
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
